### ISSUE TITLE
Use Traits to completely modularise polynomial commitment scheme 

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#121]
Currently the Commitment Scheme is loosely coupled with the proving system. However, we only use KZG10 and import it directly. We can use traits to completely remove the specific instance of KZG10

**Comment by CPerezz** [comment]
I think we could remove the 3rd and 4th iteration labels since we will need to see common and shared data structures between different polynomial commitment schemes to generate an idea of the architecture of the Trait system that we will implement for this.

**Comment by marta-belles** [comment]
Outdated.
