### ISSUE TITLE
Test whether K1 and K2 form coset generators for BLS12-381

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#130]

**Comment by CPerezz** [comment]
Starting by this resources that @decentralisedkev found: https://math.stackexchange.com/questions/507743/two-elements-are-in-the-same-coset-of-s-iff-their-difference-is-in-s , we will find and test generators and then, hardcode them into the repo as suggested in #131

**Comment by CPerezz** [comment]
To check if the difference is in `S`, we would need to check them order. But which is the order of the coset that we're expecting to get?

**Comment by CPerezz** [comment]
Same as #131

**Comment by EDGDrummond** [comment]
This issue is a subset of issue #244. I will close this issue and assign myself to the other issue.

**Comment by Bounce23** [comment]
Slight misunderstanding. #244 is the PR that is used to solve this issue. 

Will be reopened, 244 will be solved with this PR, then we'll move it to review.

**Comment by marta-belles** [comment]
Outdated. Besides, this tracking issue was already closed: https://github.com/dusk-network/plonk/issues/235.
