### ISSUE TITLE
Compute the 4n evaluations for vanishing poly in the preprocessing stage

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#140]
It would increase the performance since we will save time computing inverses and doing the `ifft` for the elements of the quotient_poly IMO.

Any thoughts @decentralisedkev ?

**Comment by kenshamir** [comment]
There is a comment here regarding this: 

https://github.com/dusk-network/plonk/blob/master/src/constraint_system/standard/quotient_poly.rs#L75

**Comment by decentralisedkev** [comment]
Wrong account.

There is a comment here regarding this: 

https://github.com/dusk-network/plonk/blob/master/src/constraint_system/standard/quotient_poly.rs#L75

**Comment by CPerezz** [comment]
Exactly! I'll take it and implement to then re-run the benchmarks and check the gains!
