### ISSUE TITLE
Use &Slice istead of &Vec for `ifft` and `fft` to increase performance

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#142]
Right now we need to allocate the vector to then re-size it and then perform the `best_fft` fn.
Check the actual impl:
https://github.com/dusk-network/plonk/blob/4d0fa12efe943c596531b4259ac5df0037868313/src/fft/domain.rs#L110
https://github.com/dusk-network/plonk/blob/4d0fa12efe943c596531b4259ac5df0037868313/src/fft/domain.rs#L119
This takes a `&[Scalar]` as evals, so the only reason to allocate a `Vec` before is to resize it. So we should implement that resizing for Slice.

And the same happens for `ifft`.

This would also be good since we will be closer to have a `no_std` impl.

**Comment by CPerezz** [comment]
After some time thinking on a solution, I don't see any way to avoid that unless using `unsafe`.

Currently Rust does not support VLA (Variable-Length-Arrays) so doing the `resize` requires allocation per-se.

Any ideas @kevaundray ?  Go for unsafe? Or you prefer to close it?

**Comment by kevaundray** [comment]
Closing as unsafe is not a viable option. We also have not checked how much will be gained from doing this
