### ISSUE TITLE
Polynomial_from_coefs_slice should not allocate the coefs

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#143]
Currently, the implementation looks like:
```rust
/// Constructs a new polynomial from a list of coefficients.
    pub fn from_coefficients_slice(coeffs: &[Scalar]) -> Self {
        Self::from_coefficients_vec(coeffs.to_vec())
    }
```

It makes no sense to get a ref to an slice and allocate a `Vec` then. 

So we should provide a propper impl that benefits from `Slice`

**Comment by CPerezz** [comment]
As in #142 unsafe seems the only way to optimize/solve this since `Polynomial` is holding a `Vec<Scalar>` inside instead of a `&[Scalar]` or a `Cow<[Scalar]>`. 

The only way without changing the struct fields would be something like: 
```rust
/// Constructs a new polynomial from a list of coefficients.
    pub fn from_coefficients_slice(coeffs: &[Scalar]) -> Self {
        let mut res = unsafe {
            Self {
                coeffs: std::mem::transmute_copy(&coeffs),
            }
        };
        // While there are zeros at the end of the coefficient vector, pop them off.
        res.truncate_leading_zeros();
        // Check that either the coefficients vec is empty or that the last coeff is
        // non-zero.
        assert!(res
            .coeffs
            .last()
            .map_or(true, |coeff| !(coeff == &Scalar::zero())));

        res
    }
```
Not sure it will even work..
Any thoughts @kevaundray ? If we're planning to support `no_std` at some point, would be nice to consider on 5th or 6th iteration to change the `coeffs` field type.

**Comment by kevaundray** [comment]
Closing for now
