### ISSUE TITLE
`Mul` and `Add` may cause confusion

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#162]
Using `Mul` and `Add` , may inadvertently change the circuit definition, when the user uses different scaling factors.

**Comment by CPerezz** [comment]
I added docs to the function regarding that. 
See #165 docs added for gates in `composer.rs`.

Anyway, I think that we should really be more explicit with this.

**Comment by CPerezz** [comment]
@kevaundray what about explicitly saying the width of each add and mul gate?

Like: 
`add_w3_gate_with_result`
`add_w3_gate_without_result`
`add_w4_gate_with_result`
`add_w4_gate_without_result`
`mul_w3_gate_with_result`
`mul_w3_gate_without_result`
`mul_w4_gate_with_result`
`mul_w4_gate_without_result`

**Comment by CPerezz** [comment]
@kevaundray unless we have a better solution for this now. 
(Now it's not terrible imo).

We will adress this issue for the future `1.0.0` and ship `0.1.0` with the actual API that he have for the ConstraintSystem.

Imo is the best thing we can actually do.

**Comment by CPerezz** [comment]
As we discussed, closing this will help a lot to decide if we should go for the actual proposal on #211 .

As far as I can imagine, the only way to reduce the ammount of gates that we have for `add` and `mul` gates would be to just provide one function with the following signature:
```
fn add_gate(&mut self, left: (Scalar, Varaible), right: (Scalar, Variable), fourth: Option<(Scalar, Variable)>, out: (Scalar, Option<Variable>), q_c: Scalar, pi: Scalar) -> Variable {
    // Do the matchings inside to adapt the fan in and the output need
}
```

This increases the complexity, true, but having 6 different functions for two gates it's also quite complex I'd say.

**Comment by kevaundray** [comment]
We discussed that idea in the call; it’s not intuitive because supplying a None to the third argument means that you are returning a result, but supplying a None to the fourth argument means that you are not using the result.

Let’s keep this issue open for now and merge the initial prover/verifier abstraction.

If we get a lot of feedback stating that the API is confusing, then let’s consider a change based on the feedback of new users.

**Comment by CPerezz** [comment]
Ye, I was just leaving the feedback so we can always see it.

Fine for me
