### ISSUE TITLE
Improve documentation on pub modules submodules and structs.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#166]
Atm, whith the merge of #165 we have a very basic documentation for the repo. We should:

- Decide which functions, traits and structs we expose to the end user. Set `pub(crate)` or `pub(self)` others. 
- Improve documentation at module-level giving an explanation of what that module contains, what is it used for and how.
- Improve struct and fn doc comments.

**Comment by CPerezz** [comment]
IIUC @kevaundray was going to work on this in order to improve the docs so I'm assigning it to him.

**Comment by CPerezz** [comment]
@kevaundray Proabably it would be nice to point in the comments of this fn:
https://github.com/dusk-network/plonk/blob/b175d6a1d6cce2ac9aa527b588f9b6f31a297156/src/fft/domain.rs#L49
That it will fail if the size is bigger than the `TWO_ADACITY` of `Bls12_381` returning a `None`.

We should also consider if it would be better to use `Result` instead of `Option`.

**Comment by CPerezz** [comment]
@kevaundray can this be closed? 
AFAIK you mentioned on our latest call that the  code comments and the doc comments were correct and enough.

**Comment by kevaundray** [comment]
Yep, closing now. However, this is an ongoing issue so documentation will still be improved.
