### ISSUE TITLE
Research & Implement Poseidon252 custom gate for TurboComposer

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#168]
In order to decrease the amount of gates required to perform a Poseidon hash round (Actually 2300/hash for PLONK basic composer (improvements pending)) we will need to research on @khovratovich proposal for the custom PLONK gate for Poseidon.

If I'm not mistaken, the doc only considers a fan-in-two Composer (the basic one) so maybe we could also decrease more the gates by using the fan-in-three TurboComposer that the currently have implemented in `master`.

@kevaundray @khovratovich could you post the updates on your research/implementation on that topic here? So we can keep track of it?

This issue is an extension of #145

**Comment by kevaundray** [comment]
Does not seem to be a way to optimise, unless we increase the width of the program. 

Closing for now,  unless we later decide that this increase in width is justifiable to shave off  ~110 constraints
