### ISSUE TITLE
Remove field `domain_size_as_scalar` for `EvaluationDomain`

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#179]
The field just repeats something that we already have stored on the same structure.

Currently `EvaluationDomain` looks like:
```rust
pub struct EvaluationDomain {
    /// The size of the domain.
    pub size: u64,
    /// `log_2(self.size)`.
    pub log_size_of_group: u32,
    /// Size of the domain as a field element.
    pub size_as_field_element: Scalar,
    /// Inverse of the size in the field.
    pub size_inv: Scalar,
    /// A generator of the subgroup.
    pub group_gen: Scalar,
    /// Inverse of the generator of the subgroup.
    pub group_gen_inv: Scalar,
    /// Multiplicative generator of the finite field.
    pub generator_inv: Scalar,
}
```
Instead of having `pub size_as_field_element: Scalar,` we could basically implement a function as a "getter" that takes the field `size` and turns it into a `Scalar`.

This will reduce the redundancy and 32-34 bytes on the serialized struct.

**Comment by kevaundray** [comment]
Why do you serialise the EvaluationDomain struct?

**Comment by CPerezz** [comment]
Because it's part of the `PreProcessedPolynomial`, which is part of `Widgets` which is part of `PreProcessedCircuit`.

So I need serde to know how to de/serialize all of the `PreProcessedCircuit` fields if I wanted to close #170

**Comment by kevaundray** [comment]
@CPerezz Isn't there a way to ignore a field, when serialising and deserialising?

**Comment by CPerezz** [comment]
@kevaundray 
If the field is inside the struct, should mean that it's part of it and so, necessary.

I need to implement the serde logic for it, otherways it's a really big mess to implement serde for `PreProcessedCircuit` directly since i have to deal with custom structs that are not serializable.

Also, We need all of the info on the `PreProcessedCircuit` once we deserialize it. So if I don't serialize this `EvaluationDomain` field, I'll have `PreProcessedPolynomial`s which have one field missing (which btw, is not an `Option`, so I'd need to set it with default values or something similar).

**Comment by kevaundray** [comment]
> The problem is that this will decrease the performance of the deserialization considerably since we have an EvaluationDomain for each PreProcessedPolynomial

Can you explain why it would decrease the performance considerably? The evaluation domain is made up of u64s and arrays, so I thought that it would not affect the performance?

Here is the preprocessed polynomial:

```
pub struct PreProcessedPolynomial {
    pub(crate) polynomial: Polynomial,
    pub(crate) commitment: Commitment,
    pub(crate) evaluations: Option<Evaluations>,
}
```

The evaluations are Optional because the Verifier will not need them. The prover will on the other hand, so if this is a problem it only affects the Prover AFAIK. I'm still a bit sceptical as the EvaluationsDomain is a small structure.

**Comment by CPerezz** [comment]
The fact that they are optional or not doesn't affect directly this.
The problem is that to be able to serialize a `PreProcessedPolynomial` I need to define the serialization logic to:
- `Polynomial`
- `Commitment`
- `Option<Evaluations>`

Then, this means that I need to implement the serde traits for `Evaluations` which contain an `EvaluationDomain`.
I can ignore the field on de se/deserlialization. But I think that the "common sense" option is basically to get the same once you deserialize the data.

**Comment by CPerezz** [comment]
After discussing it with @kevaundray , it's probably not worth it to remove the field since it allows to cache the value and not build it's representations all of the time.

So I'm closing the issue for now.
