### ISSUE TITLE
Improve Proof deserialization times

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#191]
Currently deserializing a `Proof` takes almost the same time to copute it's verification.

So since the verification relies directly on the `pairing` and we can't optimize much there, it would be nice to explore ways to improve the deserialization of the `Proof` struct to speed up the overall verification process that happens on the Dusk Network.

Currently, as the following flamegraph shows, the 99% of the time taken by the deserialization is indeed product of the `decompression` process of the `G1Affine` points (also known as `Commitments` for plonk).

![](https://user-images.githubusercontent.com/37264926/79556801-da5f7380-80a1-11ea-9bd1-711ac34e2a27.png)

So probably the speed ups or improvements in performance pass from improving the `decompression` process in `bls12_381` curve crate.

**Comment by kevaundray** [comment]
I think we can close this, as the increased times are due to the subgroup checks, which is a necessity.

We can open up a new issue on improving the subgroup checks, however I think this will not be a priority anytime soon.
