### ISSUE TITLE
Remove PublicParams trimming and EvaluationDomain computation responsabilities to end-user

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#196]
Currently, the end-user needs to do the following in order to generate a `PreProcessedCircuit` once the `Composer` has been filled.

```rust
let mut composer = StandardComposer::dummy_composer(98769usize);
let circ_size = composer.circuit_size();
    let eval_domain = EvaluationDomain::new(circ_size).unwrap();
    let (prover_key, verifier_key) = pub_params
        .trim(2 * composer.circuit_size().next_power_of_two())
        .unwrap();

    // Now we can finally preprocess the circuit that we've built.
    let pre_processed_circ = composer.preprocess(&prover_key, &mut transcript, &eval_domain);
```

The goal should be that the trimming and the `EvaluationDomain` computatuin that we need to provide to the `preprocess()` function should be taken away from the user-responsabilites and we should do id "behind the scenes". 

It should be easy since we already have all of the values we need to do that inside of the `preprocess()` fn scope (Composer.circuit_size() and also we can just receive a `&PublicParameters` and trim them inside. (This will add more time to the pre-processing but we should effectively just `preprocess` a circuit once, and re-use it all of the time for the same kinds of `Proof`s.

**Comment by kevaundray** [comment]
The Prover and Verification abstraction will take care of this
