### ISSUE TITLE
Enable check_circuit_satisfied behind a `trace` or `debug` feature

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#197]
This goes somehow related with #193 .

It would be nice to expose this function so it's easier for the end-user to some-how debug them circuit and understand where do they have an error.

It will also be nice to include a more-complex and complete feature that targets these topics more in depth and with a more useful implementation for debugging the circuits that we're building as a `Prover`.

**Comment by kevaundray** [comment]
Merged in #200
