### ISSUE TITLE
Remove coupling of the Examples with the Constraint System

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#206]
Currently modifying the constraint system will break the examples in an annoying way.

The preprocessed circuit is hardcoded to a specific version of the constraint system. While the verification procedure is linked to the most recent version.

This means we will need to keep updating the hardcoded preprocessed circuit, each time we modify the constraint system.

**Comment by CPerezz** [comment]
My idea is to create a 3.0 and 3.1 examples. 

- 3.0 will show how to pre-compute the circuit, params etc..
- 3.1 will be the same as the actual 3-
