### ISSUE TITLE
KateX seems to not be loading correctly for the notes

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#214]
If you check https://dusk-network.github.io/plonk/dusk_plonk/notes/commitment_schemes/index.html

It seems that kateX is not being loaded correctly and so the info is not displayed on a correct way.

We should fix this.

**Comment by CPerezz** [comment]
This is the message docs.rs is showing:
```
error: error reading `.cargo/registry/src/github.com-1ecc6299db9ec823/katex-doc-0.1.0/katex.html`: No such file or directory (os error 2)
[INFO] [stderr] 
[INFO] [stderr] error: Could not document `dusk-plonk`.
```

@Bounce23  you also assigned this issue. Are you going to finish it this week?

**Comment by Bounce23** [comment]
Yes @CPerezz 
This is one of 3 issues, I have,  that are on different branches to be pushed and done before the Monday call.
