### ISSUE TITLE
Remove "parallel" Cfg features not declared in Cargo.toml

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#219]
I've seen that we currently have this conditional compiling arg here:
https://github.com/dusk-network/plonk/blob/a09c14ecd45054a841dfa93147fd4f32c6fe550e/src/fft/domain.rs#L435

Same here:
https://github.com/dusk-network/plonk/blob/a09c14ecd45054a841dfa93147fd4f32c6fe550e/src/fft/domain.rs#L455
Here:
https://github.com/dusk-network/plonk/blob/a09c14ecd45054a841dfa93147fd4f32c6fe550e/src/fft/domain.rs#L505

But we don't have any "parallel" feature declared on our `Cargo.toml` nor the intention to add one AFAIK.

Should this be removed?

**Comment by kevaundray** [comment]
Hi, yeah I think this can be removed. This was initially trying to mirror zexe, but I have not see any problem with using environment variables on Rayon.

**Comment by CPerezz** [comment]
This hasn't been removed yet.  And should be since we don't have any `parallel` feature.
