### ISSUE TITLE
Fix import paths for errors

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#232]
When importing an error variant, the import path contains redundancy.

For example:

`use super::proof_system_errors::{ProofError, ProofErrors};`

**Comment by CPerezz** [comment]
It doesn't. ProofError and ProofErrors are different things.
While one is the Struct that defines a Custom error derived from `failure`, the other contains the error variants.

Not sure this is a real issue.

**Comment by kevaundray** [comment]
Oh so I was referring to the import path redundancy, We say we are importing a proof system error, then we say we want to import a ProofError. If the namespace is proof_system_errors, then I don't think we need to say we are importing a ProofError.

I think the problem with ProofError and ProofErrors is for another issue, as it's not immediately clear what the difference is between the two.

**Comment by CPerezz** [comment]
So one of them is the Generic error for this namespace while the other type which is an enum contains the specific type of error that ocurred on the namespace.

One encapsulates the others.

This is helpful to users that want to have `cause` and `backtrace` fields regarding the error.
Check `failure` docs for more info.

**Comment by CPerezz** [comment]
@kevaundray did you checked that?

**Comment by CPerezz** [comment]
@kevaundray I belive we can close this since this code was already refactored in #277

**Comment by CPerezz** [comment]
Closing since this no longer applies.
