### ISSUE TITLE
Refactor Examples folder

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#233]
Currently, the examples are not automatically tested when `cargo test` is ran.

- We can move the examples to an integration test folder, so they are automatically tested when `cargo test` is ran.

-  We can also remove the hardcoded circuits, because I think we can assume that the user knows how to save and use SERDE. 

If we want to show the user how to use a previous preprocessed circuit to prove the same statement with multiple witnesses, we can preprocess once and just re-use the pre-processed circuit in memory, instead of using lazy statics. 

This means that the example folder will only contain various examples of different gadgets.

**Comment by CPerezz** [comment]
I think examples are fine as how we have it now. We basically show how we would use plonk.
Anyway, happy to hear suggestions.

Related to the tests, they are compiled when you run `cargo build` but you need to `run` them to see if they pass.
This is the "de-facto" way of doing examples in rust mate. So not sure that we should move them.

**Comment by kevaundray** [comment]
I think the way that bulletproofs does it is clearer and you only need to remember to run `cargo test`. 

I have seen the `Examples` folder, I think this way is good because the user immediately knows that the folder contains examples, whereas it may not be quite as obvious to look into the integration tests.

In terms of friction, I think it is better to have one command to check that every test including the examples are working. Instead of running cargo test to see if your tests pass, then cargo build to check if your examples are still passing, which many users may not remember to do.

The hardcoded preprocessed circuits are definitely not needed, and similar to the previous point, once the composer changes, you will need to re-save the hardcoded preprocessed circuit. If we assume that the users will know how to serialise and deserialise a struct, then it can be removed.

**Comment by CPerezz** [comment]
I agree on that, but only users that contribute will need to worry about that. No other user will need to run the examples. They're just examples to see how to structure your code.

Anyway, it's fine, let's see the refactor and how it looks!

**Comment by CPerezz** [comment]
Now that I think about this. It will probably be better to first go for #237 and #235  and #234  before we refactor the examples. 

Otherways we will need to do it a lot of times if the API changes.
WDYT  @kevaundray ?

**Comment by kevaundray** [comment]
AFAICT most of those issues except do not affect the API, so the examples would remain relatively untouched.

There are two that might:

#234  - There is no clear plan on how/if it will be done in the near future. So the randomised constraint system _may_ break the API, but it not's a priority right now. This idea was taken from bulletproofs, and since creating the issue, it may be that in most cases it is not needed, since the circuits are padded to the next power of two anyways. I believe there is also an issue open in bulletproofs, regarding it being provably secure.



#237 - In particular, `Split Prover and Verifier keys` , this change should only require a few line changes in the API AFAICT.

**Comment by CPerezz** [comment]
Makes sense. 
I was also talking in terms of priority. Since the examples now do it's job which is show how the lib should be used. 
I agree with you that your proposal is good and makes sense, but maybe some other issues are more "valuable" atm.

**Comment by CPerezz** [comment]
Since this issue was opened, the `examples` folder was removed. 

So we should first add it back.

**Comment by CPerezz** [comment]
We need to add the examples back first as #346 says. So we can close that.
