### ISSUE TITLE
Add more descriptive benchmarks

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#238]
The benchmarks should ideally :

- compare against other well known proving systems, so that others can understand what the relative performance is.

- Compare against different circuit sizes.

- Since the ratio of addition gates to multiplication gates, plays a part in the benchmarks, [See PLONK paper] we should also give the worse case and best case ratio.

There are also use-case specific benchmarks which may be useful, such as Pedersen hashes and SHA256 circuits in each proving system.

This is a bit more in depth and does not hold high priority at the moment. However, in the end I think it would be good to give the end user a quick summary of whether this library could fit into their stack.

**Comment by CPerezz** [comment]
I like the idea, and makes complete sense!
