### ISSUE TITLE
Clean up permutation module

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#239]
There are a few issues with the permutation module:

- The function names are not that descriptive 

- It requires a better abstraction. If we think in terms of multisets, it may be easier to understand what is happening.

- We can most likely abstract away the accumulating product computation into a separate module. However, I'm not sure how beneficial this would be.

- It requires more documentation which may go hand-in-hand with the above three points

**Comment by CPerezz** [comment]
As mentioned on other issues, I would go for the new features first.

Then, once we have #273

**Comment by CPerezz** [comment]
This can be considered Stale. Closing.
