### ISSUE TITLE
Move gate specific methods to their own file

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#240]
Currently, the range gate, logic gate and arithmetic gates are all in one file along with their tests.

For the most part, this is not a problem.

The advantage of moving them to their own file is the following:

- More documentation can be added into that specific file.

- When PLOOKUP is added, there is the possibility that more items will need to be added to the composer file along with the other custom gates. 

- It is much easier to process one gate or a set of gates that do one functionality.

- Possibly, we could add more tests for that specific gate.

All of the advantages listed are things that can be done in one file, however I think that putting too many things in one file can be hard to process for the user, especially when not all of the things are linked. For example, along with gates, there are other methods such as `circuit_pad`, `circuit_preprocess` which are not related to gate functionality.

**Comment by CPerezz** [comment]
As mentioned on other issues, I would go for the new features first.

Then, once we have #273
