### ISSUE TITLE
Split  polynomial computation into Prover specific and Verifier specific modules

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#241]
This is one possible abstraction which may help in increasing code maintainability and code readability.

We could possibly have a ArithmeticProver, a RangeProver and combine them all together to get the proof.

We could possibly similarly  have a ArithmeticVerifier, a RangeVerifier and combine them all together to verify a proof.

The main aim of this is to modularise the proof system

**Comment by CPerezz** [comment]
Closing for now.
