### ISSUE TITLE
Verification fails for circuit size < 4

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/plonk#248]
The Verification procedure fails for circuits of size less than 4. This can be seen in the test named `test_prove_verify`

**Comment by CPerezz** [comment]
Well, you'll commit to zero polynomials for sure.

So it's indeed normal no? You don't have enough space to add even the dummy_constraints.

Is it realistic having a circuit-size = 4?

**Comment by kevaundray** [comment]
The dummy constraints are included in the first 3 gates, so it should pass AFAIK. Because you are essentially proving nothing.

It's an inconsequential problem, but it could be indicative or something else, so will investigate it further once the refactor has been completed.
