### ISSUE TITLE
API design discussion in respect to functions with a lot of fields

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#257]
In the current `Composer` API that we publicly expose, we have a lot of `gate-functions` that require the user to input +6 or +7 fields.

As mentioned by @ZER0 and @vlopes11 this is quite confusing, specially if you're not familiar with the library.

Therefore, it would be nice to discuss which would be a good approach (if there is) to solve this problem.

**Comment by CPerezz** [comment]
@ZER0 could you provide here your thoughts? So then @kevaundray and me can review and discuss them?

**Comment by marta-belles** [comment]
The library has been already refactored, and hence this issue no longer applies.
