### ISSUE TITLE
Variable Base Scalar multiplication custom gate implementation

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#279]
With the actual `ecc` module we have implemented for our `StandardComposer` it is not possible to perform var_base scalar mul circuits with a good performance.

Create a gadget for it which does a "work-arround" to that but as it was computed by @kevaundray , the number of constraints will be ~9000.

Therefore, since we will need that for zedger and other circuits, we should take the decision of whether is worth it or not to go for an implementation of a custom gate which provides that functionality.

The average amount of gates that it will take to do var_base scalar mul (as @kevaundray  said) was about 500 as much.

In respect to the API changes/break, the only gate that will get it's API changed is the `poly_gate` which will need to include an extra selector_poly coefficient. But the rest of the gates should still have the same API even if the underlying code changes, so I'm not worried about huge migrations TBH, it should be pretty simple to move from`v0.2.6` to the new version.

So since this is the RFC , I'll like to hear from @ZER0 @toghrulmaharramov @kevaundray @autholykos .

Also, I think it would be helpful if @kevaundray could provide some sort of "time estimation" for this impl. 

See #276 to get some background

**Comment by autholykos** [comment]
Provided that this is quite a self-contained change, I would propose to move on with it and bump PLONK library version accordingly. As soon as @kevaundray provides some estimation we can decide whether it makes sense to go directly with the new version on Zedger's implementation or do the workaround and postpone the upgrade at a second moment. @ZER0?

**Comment by CPerezz** [comment]
The estimation is 2 days of work for doing this and one for doing the gadget more or less. So I think it's worth it. Do you agree @autholykos ? In that case, as it was agreed on the standup, we will move on with that.

**Comment by autholykos** [comment]
Green light!
