### ISSUE TITLE
ECC Scalar multiplication - Private generator

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/plonk#281]
Currently the `dusk_plonk::constraint_system::ecc::scalar_mul` accepts the secret as `Variable` and `generator` as open.

We need to have the ability to input the generator secretly.

One use case for that is the ElGamal encryption. The cipher is defined as follows:
* M - Message
* P - Public
* G - Generator
* s - Secret
```rust
let K = s · G;
let C = M + s · P;
```

The broadcasted information is the tuple `(K, C)`. The protocol itself doesn't force the broadcast of `P`, but this would be required if we want to prove the knowledge of an encrypted message if `scalar_mul` demands an open generator. Ideally, the circuit would be as follows:

`elgamal_message_knowledge(s: &Variable, P: &Point, G: &ExtendedPoint, M: &Point)`

We would then proceed with the following pseudo-code
```
K = scalar_mul(s, G)
C = scalar_mul_witness(s, P)
C = curve_addition(C, M)
return (K, C)
```

**Comment by Bounce23** [comment]
As it stands the GENERATOR is a fixed jubjub point and there is no function to compute a random one. So in essence the point can always be seen.  As I see in your code on the PR, a new extended GENERATOR is made. We would have to have a random GENERATOR function and then hide it.

**Comment by CPerezz** [comment]
We cannot generate random generators since they should be part of the selector polynomials (Prover & Verifier keys) if possible. And therefore, this will lead into re-usability problems.

**Comment by kevaundray** [comment]
> As it stands the GENERATOR is a fixed jubjub point and there is no function to compute a random one. So in essence the point can always be seen. As I see in your code on the PR, a new extended GENERATOR is made. We would have to have a random GENERATOR function and then hide it.

You can compute a random generator by computing a random scalar and doing scalar multiplication using the known generator of prime order.

> We cannot generate random generators since they should be part of the selector polynomials (Prover & Verifier keys) if possible. And therefore, this will lead into re-usability problems.

We can use random generators, however scalar multiplication on `master` currently only works for fixed base scalar multiplication, this is where the algorithm fixes the point for all proofs. This works for the usual use cases such as Pedersen Commitments. However, this is different to the case where you want a different generator _possibly_ per proof.

If you can avoid variable-base scalar multiplication it would be good, as it is roughly 6 constraints per bit without the scalar decomposition, while fixed-base scalar multiplication is 1 constraint per bit with scalar multiplication with a possible optimisation making it 0.5
