### ISSUE TITLE
Implement formal benchmarks.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#317]
We had benchmarks when we launched `0.1` but with all of the refactors to the API it would have taken a lot of time to keep them up to date.

Now that the lib is more stable as well as the API(at least for the basic stuff) it would be nice to be able to obtain benchmarks for the most critical parts of our code.

**Comment by autholykos** [comment]
Moved the issue into the dedicated Epic dusk-network/rusk-vm#119
