### ISSUE TITLE
Implement Plonk with Lookups 

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#325]
This library contains an implementation of the [PLONK](https://eprint.iacr.org/2019/953.pdf) protocol. 

In order to reduce the proof sizes, for specific plonk operations, there is a paper on plonk using lookup tables. Called [plookup](https://eprint.iacr.org/2020/315.pdf). 

This epic will require documentation for each step to provide clarity between people involved in the process.

**Comment by autholykos** [comment]
Moved to the Plookup Epic
