### ISSUE TITLE
Implement min constant generics

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#337]
Currently, the api allows the user to build two different arity lookup tables. Either 3 or 4. 

The former is for witness of single operations types for lookups and the latter is for concatenated lookups. Instead of having both structs, we should implement min constant generics to have rules that permeates both use cases.

**Comment by CPerezz** [comment]
@Bounce23 does this still apply to your plookup impl?

**Comment by CPerezz** [comment]
Closing due to no further reply
