### ISSUE TITLE
Question: Can plonk convert any program to circuit which support?

### ISSUE THREAD

**Issue by DreamWuGit** [dusk-network/plonk#340]
Assume I have my own customized program , maybe write in rust or not (i.e  an java program ),  and some data to input. 
Can I use plonk to generate running result proof and let others validate its correctness ?
per my understanding,   such include two steps required:  
(1) Convert my program to circuits which plonk literature recognize 
(2) Generate proof for other verifier 

I look roughly at the plonk code , didn't find the first step functions related., however it seems to be common used case here for zero knowledge system from user perspective .  

Appreciate your help &guidance ,Thanks !

**Comment by Bounce23** [comment]
Hello @DreamWuGit , 

The short answer to your question is yes. 

I would recommend taking a look to the API and see how to construct your customised program using the `composer` within PLONK.  [Here](https://www.youtube.com/watch?v=dhotx3AaiKs) is a video of how to construct operations using the PLONK circuit builder. 

As for constructing circuits which PLONK recognises - this may come down to some particular cryptography or circuit representations. For example, operations expected to be made inexpensively in R1CS they may not be cheap to have PLONK proof constructed over them. 

It is possible, and likely, for proofs to be created by one party and verified by another. As long as they share the same transcript, this can be done. As proving times are larger than verification times, the proof could be computed by a full node and the verification computed at a later date by a blockchain user.

**Comment by CPerezz** [comment]
> Assume I have my own customized program , maybe write in rust or not (i.e an java program ), and some data to input.
The "Lingua Franca" of the PLONK proving system of this crate is: Bls12_381 + JubJub. These are the two curves used to express any kind of data in the PLONK constraint system. Meanwhile you can convert your data/statements to this types, you can use this repo to work using ffi from any other language.

> Can I use plonk to generate running result proof and let others validate its correctness ?
Definitely. You have different ways to do so. Being the easiest the following:
https://github.com/dusk-network/plonk/blob/master/src/circuit_builder.rs#L327-L369

Using the `Circuit` trait is the easiest way to set up yourself with this lib. Just follow the example that I attached above. 

Closing the issue for now. If more help is needed, feel free to re-open or create a new one. :smile:

**Comment by DreamWuGit** [comment]
Thanks @Bounce23 @CPerezz for your info, I see circuit builder can build various gates step by step,  what I am mostly interested in is for complex program logic(i.e. > 10000 gates constraint), seems it is unpractical to build it manually like this . so is there any tools  help auto build it for given program ?

**Comment by CPerezz** [comment]
Hey @DreamWuGit . `10000` constraints is quite small I would say. 
Just to make you understand a bit better, functions associated to the `StandardComposer` may include more than one constraint. Indeed can add hundreds. This is not R1CS, where you can only add and multiply in the ConstraintSystem. 

PLONK introduces custom-gates which are an optimized version of some operations such as [https://github.com/dusk-network/plonk/blob/fc184b40cad485172296d05c2fc3bf31513fd1c9/src/constraint_system/ecc/scalar_mul/variable_base/mod.rs#L12](elliptic curve addition/multiplication) or [https://github.com/dusk-network/plonk/blob/fc184b40cad485172296d05c2fc3bf31513fd1c9/src/constraint_system/range.rs#L15](range checks) or [AND/XOR ops](https://github.com/dusk-network/plonk/blob/fc184b40cad485172296d05c2fc3bf31513fd1c9/src/constraint_system/logic.rs#L298-L310).

Each of this functions will add the logic for the operation (constraints) into the CS and that means more than one, for sure. So don't be worried, I've written circuits of 2^17 constraints and it doesn't take more than 500/1000 lines depending on the circuit complexity.

**Comment by DreamWuGit** [comment]
@CPerezz  thanks , will take me time to look at the code implementation which seems difficult to fully understand.  So Can I say StandardComposer  can represents whatever complex logic program ?    
let consider an use case scenario:  
I have an old existing program maybe running for long time regarding our business.  
Now I want to adapt it run in trust execution so that others can verify output .

Now how I do ? what I can think of so far is use StandardComposer to write all circuit with plonk
but seems hard to override all the gates manually by ordinary developer.  
there are should be more efficient way to do so which I don't know?
right ?

**Comment by CPerezz** [comment]
My suggestion would be to look at the tests that we have implemented for the `Circuit` trait. inside the `circuit.rs` file. 

You should just need to create a SRS once (a big enough one) and then compile your circuits for it and prove and verify them. 
As soon as you need to change them, it's just a matter of re-implement the circuit trait with the changes, compile it again and use it trowing away the previous compiled prover and verifier keys.
