### ISSUE TITLE
Review that the API naming convention follows the Rust API guidelines

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#354]
For some data structures which are not fixed-sized, as `ProverKey` or `PublicParameters` we should make sure that the API names related to de/serialization follow [the rust API guidelines](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv)

**Comment by autholykos** [comment]
Fixed by #434
