### ISSUE TITLE
Audit Plookup Branch

### ISSUE THREAD

**Issue by autholykos** [dusk-network/plonk#358]
This includes the whole PLOOKUP proving system and specifically:
- A library containing an implementation of the PLONK protocol.
- A paper on plonk using lookup tables. Called plookup aiming to reduce the proof sizes, for specific plonk operations.
- thorough documentation for each step so to provide clarity between people involved in the process

**Comment by Bounce23** [comment]
This new epic is reflective of the work required to audit this branch, on the feedback thats pending aswell as its expected release as its own branch.
