### ISSUE TITLE
Add descriptions of how the three most promising chosen recursive proving systems work

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#365]
As part of our work on the research of recursion, we have chosen to explore 3 potential options for recursive proofs, these may encompass similar recursive protocols but with different techniques. 

These are: 
- Halo; recursive proof without trusted set up. (This includes Halo 2)
- Snarks without pairing curves which use private aggregation
- Single layer recursion

These three types of systems require documentation on their outline, including linked papers and resources, into the R&D [GitBook](https://app.gitbook.com/@dusk-network/s/dusk-r-and-d/)

**Comment by EDGDrummond** [comment]
Detail on the potential routes has been added to gitbook.
