### ISSUE TITLE
Compare Halo & PLONKy

### ISSUE THREAD

**Issue by EDGDrummond** [dusk-network/plonk#367]
These two recursive proof implementations look the most promising, so the next step is to look at them in more detail and document their differences; of primary importance are their relative speeds, and their integrability with Dusk's current system.

Note that final outcome of this issue should be:

- A document comparing the strengths and weaknesses of these two implementations
- A note on whether there would be any practical problems implementing them with Dusk

**Comment by Bounce23** [comment]
There has been some miscommunication, PLONKy is a code base that uses halo. So the title of the issue ought to be changed.

**Comment by Bounce23** [comment]
Requires changes to documentation. (Issue title)

**Comment by EDGDrummond** [comment]
This issue arose from some miscommunication, the correct issue is #365. This issue will be moved to the closed heading, and issue 365 will be worked on.
