### ISSUE TITLE
Understand Plonky (recursivity based on Plonk and Halo)

### ISSUE THREAD

**Issue by marta-belles** [dusk-network/plonk#369]
`Plonky` is a prototype implementation of recursive proofs based on [PlonK](https://eprint.iacr.org/2019/953.pdf) and [Halo](https://eprint.iacr.org/2019/1021.pdf). We want to understand how `Plonky` works and determine how suitable and useful it can be for Dusk.

Resources:

- [Mir protocol](https://mirprotocol.org/blog/Fast-recursive-arguments-based-on-Plonk-and-Halo)
- [Plonky implementation](https://github.com/mir-protocol/plonky)
- [Plonk Café discussion about Plonk](https://www.plonk.cafe/t/plonky-recursive-proofs-based-on-plonk-and-halo/63)

**Comment by marta-belles** [comment]
For some weird reason, I created the same issue twice. I will deleate this one from GitHub when synchronized with ZenHub. For now, go to issue #3.

**Comment by Bounce23** [comment]
Issue closed because of redundancy (duplicate issue).
