### ISSUE TITLE
Can we use Plonky on BLS12_381? 

### ISSUE THREAD

**Issue by marta-belles** [dusk-network/plonk#373]
Plonky uses BLS12_377 and Tweedledee/Tweedledum curves. Can we use the ideas of Plonky on BLS12_381?

**Comment by Bounce23** [comment]
In addition, let's use this issue for documenting the use of Kate on a Plonky-esque scheme.

**Comment by Bounce23** [comment]
This issue will move be carried over and moved into the new milestone.
