### ISSUE TITLE
Implement proof as a trait

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#378]
To ease the different methods of proving PLONK based circuits and the arising issues with the having different fields in proof types and not wanting to make more than double the amount of code, a trait for all the shared steps ought to be implemented for the underlying proving steps.

**Comment by CPerezz** [comment]
Has this been already discussed an approved? I think we should really consider the amount of time that will take to make the lib trait-based (it was the original idea that we had with Kev). 
I'm not saying it's not good, indeed it is. What I want to point out here is that this refactor is not trivial and can be performance sensitive also. So we need to consider if now it;s the best time to do it.

Aside from that, the idea to modularize the crate and make the core trait-based is cool. I like it!

**Comment by Bounce23** [comment]
This has been discussed with a few people but I think an official discussion, preferably today, with a documentation of the outcome. 
It is possible to just do with some duplicated code but its not ideal. Issue 74 was made when there was only one type of proving algorithm.

**Comment by Bounce23** [comment]
The outcome of this will be discussed in a meeting on 1/3/21 and should be documented here to be progressed for the next iteration.
