### ISSUE TITLE
Understand and Document the step by step methods of halo infinite

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#381]
The workflow, in terms of cryptography and ultimately implementation, of Halo infinite needs to be broken down so we can use it within our PLONK protocol

**Comment by marta-belles** [comment]
Halo Infinite presents a method for aggregating PCS proofs, to reduce the task of proving evaluations of multiple commitments at multiple independent points. At this stage and after reading the paper, this is not useful for our proposal of PlonK proofs aggregation.
