### ISSUE TITLE
Understand how BLS signatures are aggregated 

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#388]
We need to understand how BLS signatures are aggregated, when auxiliary to recursive proofs. This will allow us to see how useful/feasible this solution will be for use in PLONK.

**Comment by marta-belles** [comment]
## BLS Signature Scheme
### One signature
**Key generation**
- Cyclic groups `G_1 = <g_1>` and `G_2 = <g_2>` with same prime order `p`.
- A bilinear pairing `e: G_1 x G_2 -> G_T`.
- Let `x` be a random in `Z_p*` and `y = g_2^x`.
- Let `H: {0,1}* -> G_1` be a hash function.
- The public key is the tuple `pk = (G_1, G_2, g_1, g_2, y, H)` and the private key `sk = x`.

**Signature of a message `m`**

Let `m` be an element of `{0,1}*`. The signautre is `sigma = H(m)^x`.

**Verification**

Given `(pk, m, sigma)`, the signature is valid if and only if  `e(g_2, sigma) = e(H(m), y)`.

### Aggregation of signatures

Assume `n` users, each with their corresponding BLS keys `(pk_i, sk_i)` must sign a common message `m`. 

- Each signature `sigma_i = H(m)^{sk_i}` satisfies the equation `e(\sigma_i, g_2) = e(H(m), y_i)`. 
- Multiplying the `n` equations (one per each signer) we get:
```
prod_{i=1}^{n} e(sigma_i, g_2) = prod_{i=1}^{n} e(H(m), y_i)
```
which is equivalent to:
```
e(prod_{i=1}^{n} sigma_i, g_2) = e(H(m), prod_{i=1}^{n} y_i)
```
- So, we can aggregate the `n` signatures into a single signature `sigma = prod_{i=1}^n sigma_i`.
- We can also aggregate the `n` public keys into a single one `apk = prod_{i=1}^n pk_i`.

** First attempt **

- A multisignature address `pi = (h, n)` contains the hash value `h = H(apk)`.
- A transaction for `m` contains `(m, apk, sigma)`. Each user contributes with their signature `sigma_i = H(m)^{sk_i}` and one of the parties computes `sigma`.
- To verify a transaction `(m, apk, sigma)` with respect to the multisignature address `pi = (h, n)`, only two conditions need to be checked: 
    (1) `h = H(apk)`.
    (2) `e(sigma, g_2) = e(H(m), apk)`.

This scheme is clean and efficient but there is an attack.

** Clave Rogue Attack **

Consider `n=2`. In this case, a transaction `(m, apk, sigma)` is accepted if `e(sigma, g_2) = e(H(m), apk)`, where `apk = pk_1 · pk_2`. Malicious user 1 can:
- Take a random `alpha` in `Z_p` and public key `pk_2` from user `2` and publish a _fake_ public key `pk_1 = g_2^alpha · pk_2^{-1}`. 
- Note that user 1 does not know the private key corresponding to this `pk_1`.
- Then, `apk = pk_1 · pk_2 = g_2^alpha`. 
- This way, user 1 can forge a multisignature `sigma = H(m)^alpha`, which would be accepted as a valid signature coming from users 1 and 2.

To avoid this attack, the final protocol uses a hash on the public keys. 

** Second (and last) attempt **

- A multisignature address `pi = (h, n)` has the hash value `h = H(apk')`, where `pk_i = g_2^{sk_i}` and 
```
apk' = prod_{i=1}^n pk_i^{ H_2(pk_i, {pk_1,pk_2,...,pk_n}) }
```
where `H_2` is a function that maps elements to `G_2`.
- A transaction for `m` contains `(m, apk', sigma)`, where `sigma = prod_{i = 1}^n sigma_i` and now 
```
sigma_i = H(m)^{ sk_i · H_2(pk_i, {pk_1,pk_2,...,pk_n}) }
```
- To verify a transaction `(m, apk', sigma)` with respect to the multisignature address `pi = (h, n)`, the following two conditions must be fulfilled:
    (1) `h = H(apk')`.
    (2) `e(sigma, g_2) = e(H(m), apk')`.

**Comment by marta-belles** [comment]
@EDGDrummond can you take a look at what I wrote? Maybe there is some sort of attack analogous to the clave rogue attack in what we are trying to do. I think it is interesting to know anyways:)

**Comment by EDGDrummond** [comment]
Looks good. The attack here manipulates some structure in the data (the relationship of the keys to one another) in order to fake the signature. Our data does not have this structure, but of course there is other structure our data that may be manipulated. In line with other results our structure seems safe however.
