### ISSUE TITLE
Adapt/Compare sec. 2.4.2. from [2020/499] to our PlonK batching proposal

### ISSUE THREAD

**Issue by marta-belles** [dusk-network/plonk#390]
Section 2.4.2 from [Proof-Carrying Data from Accumulation Schemes](https://eprint.iacr.org/2020/499.pdf) sketches an accumulation scheme for polynomial commitments based on knowledge assumptions over bilinear groups (PC_AGM). It is worth reading it through and compare/adapt the ideas from the paper to our PlonK batching proposal.

**Comment by Bounce23** [comment]
This comparison is very abstract, therefore it is quite difficult to refine the contents. However, a proposal for recursive direction has been found and this lives within a [hack md](https://hackmd.io/@plz5nZb2SvSzWpHxjV2shw/r135IkRxd/edit). A new issue will be created around concretising this hack md.
