### ISSUE TITLE
Formalising how to construct the recursive circuits.

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#392]
This [hack md](https://hackmd.io/@plz5nZb2SvSzWpHxjV2shw/r135IkRxd/edit), contains an initial suggested proposal for recursion. This issue will cover the formalisation of the circuit creation and specification.

**Comment by marta-belles** [comment]
We reached to the conclusion that it is not possible to write recursive circuits in the proposal as it right now. We submitted a new issue (#400) to determine what is the current problematic and see if there is any way to fix it or it is better to follow a new approach.
