### ISSUE TITLE
Fix notation for primes p, q, r.

### ISSUE THREAD

**Issue by marta-belles** [dusk-network/plonk#401]
To avoid misunderstandings, we must agree on a common notation for the different prime fields and group orders. The resolution will be added to Dusk R&D GitBook page.

**Comment by marta-belles** [comment]
Fixed. To be reviewed and accepted by @Bounce23 and @EDGDrummond.

**Comment by Bounce23** [comment]
Comments left on draft edits in GitBook @marta-belles
