### ISSUE TITLE
Document the inner workings of the half pairing cycle

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#407]
The 'half pairing cycle' is a name given to a system which uses two different curves for recursive proof construction. 
One curve is a paring curve which conducts, proves and verifies pairing arguments for circuits. The other curve is a non pairing curve which hods an accumulator for output of proofs in another field. 

Operations on these accumulators will determine which path of recursion we take. 
This issue is intended to gain more insight into the trade offs between half pairing options.

**Comment by marta-belles** [comment]
According to [Zcash Issue 4092](https://github.com/zcash/zcash/issues/4092), it is not necessary for the inner proving system to be succinct, it just needs to allow us to outsource `F_p`-arithmetic more efficiently than it can be naively simulated in `F_q`.

**Comment by marta-belles** [comment]
@Bounce23, which two proving systems do we want to combine in our recursions? Is it Halo with PlonK?

**Comment by Bounce23** [comment]
yes
