### ISSUE TITLE
Finish Zerocaf paper 

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#418]
The Zerocaf paper is now centric around Fq arithmetic inside of Fq circuits. This is to be finished and put into Review prior to an IACR.

This Epic will have to include iterations of each of the sections and then their individual review.

**Comment by CPerezz** [comment]
Shouldn't this be added in the Zerocaf repo?

**Comment by Bounce23** [comment]
Yes, you are correct @CPerezz. This was created in the Zenhub and permeated issues. Will move to [zerocaf](https://github.com/dusk-network/dusk-zerocaf)

**Comment by Bounce23** [comment]
Closing this as new issue is recreated [here](https://github.com/dusk-network/dusk-zerocaf/issues/100).
