### ISSUE TITLE
Flesh out depth-2 recursion paper over BLS12-381 

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#419]
The BLS12-381 requires a depth 2 recursion for aggregation of signatures in circuit. The idea is to provide improvements, using PLONK, to existing protocols which use chain recursion. Our past documentations will now go under a collation into a first improvement over BLS signatures in circuit.

**Comment by CPerezz** [comment]
This does not belong to this repo. 

Can we close it @ZER0 @Bounce23 ?

**Comment by Bounce23** [comment]
Yes, we can now close. The solution was found and documented in GitBook.
