### ISSUE TITLE
Read "One Way Accumulators: A Decentralized Alternative to Digital Signatures"

### ISSUE THREAD

**Issue by marta-belles** [dusk-network/plonk#421]
It seems the content of the article _One Way Accumulators: A Decentralized Alternative to Digital Signatures_ can avoid us the need to implement signature recursion.

**Comment by EDGDrummond** [comment]
This paper unfortunately doesn't seem to be of use to us. Its one way accumulators are of the Merkle tree-type, i.e. they allow you to simply prove set membership of a particular entry - but they do not allow us to confirm the whole set is what we want it to be in one. Perhaps we can make use of some of the ideas, but it's not as helpful as hoped.
