### ISSUE TITLE
Impl From trait for Commitment conversions

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#433]
Actually in our repo, we have implemented Commitment as a wrapper type over `dusk-bls12_381::G1Affine`.

https://github.com/dusk-network/plonk/blob/master/src/commitment_scheme/kzg10/mod.rs#L95-L104

But instead of implementing the conversions from Affine and from Projective on that way, we should implement the `From` trait.

**Comment by oriolval** [comment]
Hi mate, I will try to solve the issue!
