### ISSUE TITLE
Consider removing EvaluationDomain struct from Evaluations

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#436]
We usually store multiple `Evaluations` inside the same structure (`ProverKey` is an example of that). It's really sub-optimal to store the  same `EvaluationDomain`  across all of the `Evaluations` of the structure. 

Therefore, we should consider how viable and logical is the removal.

**Comment by moCello** [comment]
Currently we are storing 
Removing the `EvaluationDomain` from the `Evaluations` structure will decrease the size of the ProverKey significantly

**Comment by marta-belles** [comment]
Outdated.
