### ISSUE TITLE
Document method of hashing SHA-3 for whole blocks 

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#472]
In line with this iteration and epics, we ought to find an efficient way to hash all the fields within an epoch block. 

This issue should encompass: 
- Which type of epoch blocks we have i.e. first and/or last 
- What fields are contained in each one 
etc

**Comment by EDGDrummond** [comment]
Documenting begun in a google doc, but this will be put on hold again as we implement the hashing in code - the documentation will be finalised after the code is done.

**Comment by CPerezz** [comment]
@Bounce23 this should be transfered away from this repo please. I think is the last issue missing.
