### ISSUE TITLE
PR Sonny paper - ZeroCaf repo

### ISSUE THREAD

**Issue by marta-belles** [dusk-network/plonk#478]
The most recent version of the Sonny paper is on overleaf. The recent changes should be updated in the ZeroCaf GitHub repository.

**Comment by Bounce23** [comment]
I think this issue ought to be moved to the [zerocaf](https://github.com/dusk-network/dusk-zerocaf/issues) repo @marta-belles

**Comment by marta-belles** [comment]
I close this issue and create a new one in the right repo.
