### ISSUE TITLE
Build gadget to accept minimum 2/3+1 of committee

### ISSUE THREAD

**Issue by EDGDrummond** [dusk-network/plonk#481]
Due to the nature of the proof of stake protocol the blocks can only be validated if > 2/3 of the members are honest. To enforce this we need to create a gadget which enforces a threshold using the field, `maximum_signers`, to check the fraction of the total.

**Comment by CPerezz** [comment]
Shouldn't we move this to another repo? This doesn't seem to belong to plonk

**Comment by Bounce23** [comment]
Issue closed as it has been reopened in the lightclient repo
