### ISSUE TITLE
Document how we can do half-aggregation of EdDSA signatures will be done

### ISSUE THREAD

**Issue by marta-belles** [dusk-network/plonk#482]
Recent results [(https://eprint.iacr.org/2021/350.pdf)]([https://eprint.iacr.org/2021/350.pdf]) show that it is possible to compress a set of independent EdDSA signatures to almost half their native size. The ideas of the article will be summarized in GitBook to facilitate the job of implementing the protocol in the upcoming days.

**Comment by Bounce23** [comment]
Closing as Issue moved to Cryptographic R&D repo.
