### ISSUE TITLE
use multi threads to generates various poly commit ?

### ISSUE THREAD

**Issue by DreamWuGit** [dusk-network/plonk#521]
from what I see code , both in pre process and  prove stage, lots of polynomials need to be committed,, such as :
      " let q_m_poly_commit = commit_key.commit(&q_m_poly).unwrap_or_default();
        let q_l_poly_commit = commit_key.commit(&q_l_poly).unwrap_or_default();
        let q_r_poly_commit = commit_key.commit(&q_r_poly).unwrap_or_default();
        let q_o_poly_commit = commit_key.commit(&q_o_poly).unwrap_or_default();
        let q_c_poly_commit = commit_key.commit(&q_c_poly).unwrap_or_default();
        let q_4_poly_commit = commit_key.commit(&q_4_poly).unwrap_or_default();
        let q_arith_poly_commit = commit_key.commit(&q_arith_poly).unwrap_or_default();
        let q_range_poly_commit = commit_key.commit(&q_range_poly).unwrap_or_default();
        let q_logic_poly_commit = commit_key.commit(&q_logic_poly).unwrap_or_default(); "

these polys are independent,  do it in multi threads in parallel will improve the performance regarding this type operation,  this is what I think intuitively !
anybody take a look at such idea ? is there something I'm missing ?

thanks 
Dream

**Comment by CPerezz** [comment]
Hey @DreamWuGit  thanks for the suggestion!

We are already aware of the performance improvements that we can go for on both proving and verification stages.
We will focus on this side of the crate soon. 

Anyway, feel free to submit a PR with any improvement! We would love to see it! :smiley:

**Comment by HDauven** [comment]
This should already be happening in the code.
CC: @xevisalle

**Comment by xevisalle** [comment]
Closing because the code is already run in multithread mode when doin the multiexponentiations. Splitting each call won't make any difference IMH.
