### ISSUE TITLE
Change Circuit::CIRCUIT_ID trait-associated const for an associated trait method

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#531]
Associated trait-constants are a problem when we need to return from functions things like `& impl Circuit`. Since the trait is not object safe anc we cannot make use of dynamic dispatch which is a big issue that we-ve faced a couple of times so far.

So the plan for the next release, is to change the impl for the CIRCUIT and break the API replacing the `CIRCUIT_ID` const by a simple associated function that allows object safety and therefore dynamic dispatch.

**Comment by marta-belles** [comment]
Outdated.
