### ISSUE TITLE
Missing qfixed and qvar in check_circuit_satisfied

### ISSUE THREAD

**Issue by ChihChengLiang** [dusk-network/plonk#541]
### What's wrong

The variable k in the check_circuit_satisfied should check if constraints related to q_fixed_group_add and q_variable_group_add selectors are satisfied, but the check is unimplemented now.

### How can we fix it

Add qfixed and qvar checks to the variable k

**Comment by moCello** [comment]
Not applicable anymore since `check_circuit_satisfied` doesn't exist anymore
