### ISSUE TITLE
Elaborate some general documentation about PLONK and it's different parts

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#58]
Some docs about the general PLONK functionality and it's different parts should be done on each corresponding `.rs` file where an important element is implemented:

- Composer
- Permutation
- Linearisation poly
- Constraint System
- Opening poly
- Proof
- Quotient poly
- Public Inputs
- Transcript

Nothing extra extensive but that at the same time explains why is this component used for and how it works.

**Comment by CPerezz** [comment]
Moving to 3rd Iteration milestone.

**Comment by Bounce23** [comment]
I'm doing this as atomic PR's for each paired notes files. So I will close this as the other PR's have already begun.
