### ISSUE TITLE
Plonkup - Clarify the arity structure for the tables

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/plonk#589]
**Describe what kind of specification you want to have created**
Currently `plonkup` added `PlonkupTable3Arity` and `PlonkupTable4Arity`. However, the turbo composer is implemented to support only `PlonkupTable4Arity` as in https://github.com/dusk-network/plonk/blob/add_lookups/src/constraint_system/composer.rs#L102

We need:

1) Understand if we have a clear benefit or use case to have multiple arity definitions
2) Generalize the test cases in https://github.com/dusk-network/plonk/blob/add_lookups/src/plonkup/table/lookup_table.rs#L585 to cover every table implementation (currently its covering only `PlonkupTable3Arity`

**Comment by marta-belles** [comment]
Current documentation of `plonkup` contains a section explaining how to handle multiple tables which does not match the current implementation. The document should also be changed according to the code.
