### ISSUE TITLE
Plonkup - Fix or document ignored tests

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/plonk#590]
**Describe the bug**
Some of the tests are ignored without a comment explaining why. We should either fix the problems related to these test cases or explicitly document why they should be ignored

**To Reproduce**
N/A

**Expected behaviour**
Every test case should be passing

**Logs/Screenshot**
N/A

**Platform**
N/A

**Additional context**
N/A

**Comment by ureeves** [comment]
Closed by #593
