### ISSUE TITLE
Unchecked `WitnessPoint` to `JubJubAffine` conversions

### ISSUE THREAD

**Issue by ureeves** [dusk-network/plonk#626]
There are still unchecked conversions in the code. Specifically [here](https://github.com/dusk-network/plonk/blob/add_lookups/src/constraint_system/ecc/curve_addition/variable_base_gate.rs#L29-L37). We should what pros and cons of keeping/removing them. If we decide to keep them we should comment them properly. 

This was first mentioned in [this PR](https://github.com/dusk-network/plonk/pull/625#pullrequestreview-780942983).

**Comment by moCello** [comment]
File: src/constraint_system/ecc/curve_addition/variable_base_gate.rs
```
  29   │         let p1 = JubJubAffine::from_raw_unchecked(
  30   │             self.witnesses[&x_1],
  31   │             self.witnesses[&y_1],
  32   │         );
  33   │
  34   │         let p2 = JubJubAffine::from_raw_unchecked(
  35   │             self.witnesses[&x_2],
  36   │             self.witnesses[&y_2],
  37   │         );
 
```

**Comment by ureeves** [comment]
The only conversions like these that remain in the code are in `composer.rs` and pertain to a point->point conversion. This means there are no remaining unchecked scalar->point conversions anymore. Closing.
