### ISSUE TITLE
Documentation touch-up

### ISSUE THREAD

**Issue by moCello** [dusk-network/plonk#627]
**Describe what kind of specification you want to have created**
Under the documentation module, add articles that help understand PlonK, e.g.:
- Zero Knowledge Proofs
- Finite fields of elliptic curve points
- Elliptic curve pairings
- PLONK basics
  - circuit/gates
  - polynomials
  - statement & proof systems
- Kate commitments

**Comment by HDauven** [comment]
Closing in favor of #819
