### ISSUE TITLE
Remove `bit_iterator` macro

### ISSUE THREAD

**Issue by moCello** [dusk-network/plonk#632]
**Describe what you want implemented** 
Remove the `bit_iterator` macro.

**Describe "Why" this is needed**
As far as I can see we only invoke the macro once to create `BitIterator8` so I don't see the need to have a macro for it. Creating `BitIterator8` directly is much clearer.

**Describe alternatives you've considered**
Leave as is.

**Additional context**
NA

**Comment by ashutoshvarma** [comment]
Hi, is this still need? Would be happy to drop a PR for this.

**Comment by moCello** [comment]
Sure! Just add me as a reviewer to the PR

**Comment by ashutoshvarma** [comment]
@moCello 
I'm not able to add you as a reviewer in PR, I think only owner/contributors can do that.
btw here is the PR #719

**Comment by moCello** [comment]
@ashutoshvarma I see, I'll have a look
