### ISSUE TITLE
Add permutation challenge `theta` in round 3

### ISSUE THREAD

**Issue by moCello** [dusk-network/plonk#653]
**Describe what you want implemented** 
The polynomial `z_2` in round 3 needs a permutation challenge `theta` to be computed. This seems to not be implemented yet.

**Describe "Why" this is needed**
So that the implementation matches the paper.

**Describe alternatives you've considered**
none

**Additional context**
NA

**Comment by marta-belles** [comment]
This applies to Plonkup and not plonk, so this issue no longer applies.
