### ISSUE TITLE
Eliminate `expect` in `append_output_witness`

### ISSUE THREAD

**Issue by moCello** [dusk-network/plonk#670]
**Describe what you want implemented** 
Eliminate `expect` in `append_output_witness` by propagating an error if `q_o` is `0`.

**Describe "Why" this is needed**
A malicious user can crash a plonk server by submitting a wrong proof.

**Describe alternatives you've considered**
Set a constant when `q_o` happens to be zero.
Changing the signature is preferable because it will reflect what happens internally: any proof request where `q_o` is zero is invalid.

**Additional context**
First mentioned by @vlopes11 [here](https://github.com/dusk-network/plonk/pull/662#discussion_r819401395)

**Comment by marta-belles** [comment]
This issue is related to plonkup and not plonk, so it is no longer applicable.

**Comment by moCello** [comment]
This issue is not related to plonkup but can be closed nontheless as completed.
There is no method `append_output_witness` and the only calls to `expect` that are left in the composer are in `gate_add` and `gate_mul`. In both of these cases we can safely call `expect` because we hard-code the output selector to -1.
