### ISSUE TITLE
Improve the `Polynomial` struct name

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/plonk#706]
Does this really still represent a polynomial? I would say that this is a gate / constraint

_Originally posted by @moCello in https://github.com/dusk-network/plonk/pull/700#discussion_r947670321_

**Comment by ashWhiteHat** [comment]
Plonk uses Polynomial for gate constraints as the same with Groth16 uses R1CS.
It makes sense to me but is complicated because `Polynomial` means other things too.
Does it make sense to rename it to `PlonkArithmetization` or something like that?

**Comment by moCello** [comment]
I like `Arithmetization`!
