### ISSUE TITLE
Questions about the scale of multi scalar multiplication in practical application

### ISSUE THREAD

**Issue by 20171759** [dusk-network/plonk#754]
I noticed that the project uses the "pippenger" algorithm for the calculation of multiple scalar multiplication, but the upper limit of "window_size" is 8 when segmenting scalars. When scalars and points are large, a larger "window_size" will have a better effect. So I want to know how large the scale of multiple scalar multiplication will be in practical applications.
![image](https://user-images.githubusercontent.com/57170238/229439483-6ff45197-1cf2-4d1d-8020-91e1dd5693ba.png)

**Comment by moCello** [comment]
Closing this issue since it is not relevant for the plonk repository.
