### ISSUE TITLE
Compiler failing to compile circuit.

### ISSUE THREAD

**Issue by brianfakhoury** [dusk-network/plonk#758]
**Describe the bug**
When using the example code as a main binary, the `Compiler::compile` method causes a panicked exit of the program. I believe this might be similar/related to #753 as it also appears when running `cargo test`.

**To Reproduce**
It seems any use of this function signature triggers it, though I haven't been exhaustive:

```rust
dusk_plonk::composer::compiler::Compiler
pub fn compile<C>(pp: &PublicParameters, label: &[u8]) -> Result<(Prover, Verifier), Error>
where
    C: Circuit
```

**Expected behaviour**
No circuit compile issues.

**Logs/Screenshot**

```bash
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', /Users/brianfakhoury/Desktop/plonk/src/composer.rs:927:9
```

**Platform**
 - Architecture: [Apple M2]
 - OS: [MacOS 13.4.1]

**Additional context**
Using `v0.14.1`

**Comment by moCello** [comment]
Thanks for reporting @brianfakhoury 
This seems indeed related to #753 and can be reproduced by running the example code from the README in debug mode
```
cargo test --doc
```

I created an issue to track the progress of fixing this bug: #763
