### ISSUE TITLE
Set `k` generators of the curves as generic instead of hardcoding them

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#8]
As discussed with @decentralisedkev , `k2` should be a parameter that depends on the curve.
Even `13` is usually a generator of the group, and it's the case for the curves BLS12-381 and BN256, we should use the `legendre_symbol` to check it and otherways, use another value.

See: 
https://github.com/dusk-network/plonk/blob/b23aaba56dc303b6a83d83b2ed0bee548551cf74/src/cs/permutation.rs#L64

**Comment by decentralisedkev** [comment]
We now use a single curve, so K1 and K2 do not need to generic.

We do however, need to test whether they form cosets and ideally we should generator four or five of them, then hardcode them for concepts like the TurboComposer.

**Comment by decentralisedkev** [comment]
Closing and opening a new issue to test whether K1 and K2 form cosets, and a dynamic method to generate them
